baseurl = "https://techglider.github.io/"
languageCode = "en-us"
title = "The TechGlider"

[permalinks]
    explainer = "/essay/:slug/"
    howto = "/essay/:slug/"
    opinion = "/essay/:slug/"

    review = "/review/:slug/"
    story = "/story/:slug/"

    post = "/update/:slug/"

#[[menu.main]]
#    name = "Essays"
#    url = "categories/essay"

[[menu.main]]
    name = "Reviews"
    url = "categories/review"

#[[menu.main]]
#    name = "Stories"
#    url = "categories/story"

[[menu.main]]
    name = "Updates"
    url = "categories/update"

[indexes]
    tag = "tags"
    category = "categories"

[params]
    author = "Kartik Singhal"
    subtitle = "Learning and sharing about Computer Science, programming, research & technology"

    rss = "true"

    sidebarRecentLimit = 5

    searchEngineURL = "https://www.google.com/search"

    github = "https://github.com/techglider"
    twitter = "https://twitter.com/techglider"
    slack = "https://techglider.slack.com"

[blackfriday]
    fractions = "false"
